apiVersion: labels.shahaf.com/v1alpha1
kind: NamespaceLabel
metadata:
  labels:
    app.kubernetes.io/name: namespacelabel
    app.kubernetes.io/managed-by: kustomize
  name: namespacelabel-sample
  namespace: default
spec:
  # Labels are applied to the same namespace as this CR (default) for security
  labels:
    environment: "development"
    team: "platform"
    managed-by: "namespacelabel-operator"
